# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MachComposer < Formula
  desc "MACH composer is a framework that you use to orchestrate and extend
modern digital commerce & experience platforms, based on MACH
technologies and cloud native services..
"
  homepage "https://machcomposer.io/"
  version "2.17.1"
  license "MIT"

  depends_on "git" => :optional
  depends_on "terraform"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.17.1/mach-composer-2.17.1-darwin-amd64.tar.gz"
      sha256 "032375c2cd0b3fc2ceae5e13c2e095c7c92d5914e8a8e83e1b125973a72709c5"

      def install
        bin.install "bin/mach-composer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.17.1/mach-composer-2.17.1-darwin-arm64.tar.gz"
      sha256 "f7f25a3ac7b9f965bb5a7df4d9c0bb00ddb05295d348096c64fd28ddaae1bee4"

      def install
        bin.install "bin/mach-composer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.17.1/mach-composer-2.17.1-linux-amd64.tar.gz"
      sha256 "d619e73da25626aae42633a588c1a44a58222733077d14bb8d9329d8db1d8e3f"

      def install
        bin.install "bin/mach-composer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.17.1/mach-composer-2.17.1-linux-armv6.tar.gz"
      sha256 "888ec46d727f12d693cb971743a898f9a4436e336aeca27cb1d68efbe5447576"

      def install
        bin.install "bin/mach-composer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mach-composer/mach-composer-cli/releases/download/v2.17.1/mach-composer-2.17.1-linux-arm64.tar.gz"
      sha256 "57e661c74ef2269f93634081c0243262a4c35089ff260e331970624838e8315d"

      def install
        bin.install "bin/mach-composer"
      end
    end
  end
end
