# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MachComposer < Formula
  desc "MACH composer is a framework that you use to orchestrate andextend modern digital commerce & experience platforms, based on MACH technologies and cloud native services.."
  homepage "https://machcomposer.io/"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/labd/mach-composer/releases/download/v2.0.0/mach-composer_2.0.0_darwin_arm64.tar.gz"
      sha256 "9d8d9a671c89ab3496addcfb8c1dece0fa557d2aa045cd8cc704535b3b58c582"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/labd/mach-composer/releases/download/v2.0.0/mach-composer_2.0.0_darwin_amd64.tar.gz"
      sha256 "34f78ba8eb9af0c323f6da0c7d5c5e44b5e92600765be72f52a6e9658f293fcc"

      def install
        bin.install "mach-composer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/labd/mach-composer/releases/download/v2.0.0/mach-composer_2.0.0_linux_arm64.tar.gz"
      sha256 "35ea735ed71a380fe8b1d7dafd761dde4ef28b70ee004e262fd6cff12dba4f80"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/labd/mach-composer/releases/download/v2.0.0/mach-composer_2.0.0_linux_armv6.tar.gz"
      sha256 "5136dc4820b252f4463f00444b93ab847c0c22de5ec1c0f6f9d17f19a0680be6"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/labd/mach-composer/releases/download/v2.0.0/mach-composer_2.0.0_linux_amd64.tar.gz"
      sha256 "f944c81c55a5b9391be88d5da83aa7c7d1092503d9f4e66c5bd95317c6213dc6"

      def install
        bin.install "mach-composer"
      end
    end
  end

  depends_on "terraform"
  depends_on "git" => :optional
end
