# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MachComposer < Formula
  desc "MACH composer is a framework that you use to orchestrate andextend modern digital commerce & experience platforms, based on MACH technologies and cloud native services.."
  homepage "https://machcomposer.io/"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/labd/mach-composer-go/releases/download/0.0.5/mach-composer_0.0.5_darwin_amd64.tar.gz"
      sha256 "2f7c5eee9c1d97647d5bd9aa170e67d3cf54c01a78c250fd9ec9eec07812fad1"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/labd/mach-composer-go/releases/download/0.0.5/mach-composer_0.0.5_darwin_arm64.tar.gz"
      sha256 "2547f16eab7b2a545b86dd8e1c95a21e49d06b0eadd7229b0dcd3d29e67427a5"

      def install
        bin.install "mach-composer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/labd/mach-composer-go/releases/download/0.0.5/mach-composer_0.0.5_linux_amd64.tar.gz"
      sha256 "ff5e3ef673b70346338b7ba549cd105be1df76b94b29fc0ccd1d077fbcac5dbc"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/labd/mach-composer-go/releases/download/0.0.5/mach-composer_0.0.5_linux_armv6.tar.gz"
      sha256 "edde082ef7cd6da98475359a768f33994f3fd77d4ff16935f365f65554997bec"

      def install
        bin.install "mach-composer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/labd/mach-composer-go/releases/download/0.0.5/mach-composer_0.0.5_linux_arm64.tar.gz"
      sha256 "4bb2134164707c1495f072a0ef633b787d9ad5138f7511cbef4db5d859f24850"

      def install
        bin.install "mach-composer"
      end
    end
  end

  depends_on "terraform"
  depends_on "git" => :optional
end
